### ISSUE TITLE
Porkbun changing to api.porkbun.com

### ISSUE THREAD

**Issue by mateoconlechuga** [RLado/Oink#10]
Porkbun.com is migrating its API services away from `porkbun.com` to `api.porkbun.com`. This change will eventually need to be reflected in this repository, I can open a PR if you would like.

**Comment by RLado** [comment]
Thanks for the heads up! I just got the email from Porkbun support notifying the change. I'll be glad to accept your PR. I'll merge it tomorrow morning.
