### ISSUE TITLE
openrc init script for alpine

### ISSUE THREAD

**Issue by yknip0** [RLado/Oink#2]
I am using your excellent work on an alpine vm which uses openrc rather than systemd. Perhaps you'd like to include this working init script for others similarly  (Gentoo, etc) situated:
#####
#!/sbin/openrc-run

##/etc/init.d/oink_ddns                 
                                    
name="oink_ddns"                    
cfgfile="/etc/oink_ddns/config.json"  
command="/usr/bin/oink"               
pidfile="/run/oink_ddns/oink_ddns.pid"
command_background="yes"
                                                             
start_pre() {                                                
        checkpath --directory --owner root:root --mode 0775 \
                /run/oink_ddns
}
####
This file and:
# rc-update add oink_ddns default
does the job

**Comment by RLado** [comment]
Thank you for the script! I will try to include it as soon as possible. However, I do not have any experience with openrc or alpine and I have to figure out how to properly package the application and use the init script.

**Comment by yknip0** [comment]
I suspect just making the script available, and mentioning it in Readme.md, is enough. SysV and run it init scripts would be similar. Of course you could create a separate package for every distro - too much work! Thanks again

From: Ricard Lado, PhD ***@***.***>
To: RLado/Oink ***@***.***>
CC: yknip0 ***@***.***>; Author ***@***.***>
Date: Jan 1, 2024 3:24:08 AM
Subject: Re: [RLado/Oink] openrc init script for alpine (Issue #2)

**Comment by RLado** [comment]
I think you are right. Thank you for sharing your script!
