### ISSUE TITLE
Oink reports unmarshal error but operation succeeds

### ISSUE THREAD

**Issue by apple314159** [RLado/Oink#7]
Oink is reporting when compiled with go 1.23.0:
`error decoding API response: json: cannot unmarshal number into Go struct field statusResp.id of type string (status: 200)
`

The actual json response is the following:
`{"status":"SUCCESS","id":423774377}`

The problem seems to be that the struct statusResp is defined as
`type statusResp struct {
	Status  string `json:"status"`
	Id      string `json:"id"`
	Message string `json:"message"`
}
`
Changing the Id type to int instead of string fixes the problem.

**Comment by RLado** [comment]
Thank you for reporting the issue. 

I have been going through the logs on my machine and I see no such error despite having updated the DNS a few times. Could it be that the API specification was changed?

**Comment by apple314159** [comment]
I think it may be an issue with the go version. I'm using the latest 1.23.0. Maybe it's being more strict as the id is not in quotes.

**Comment by RLado** [comment]
Interesting, looking at the API documentation my code should be correct. But clearly it is not...

The [API docs](https://porkbun.com/api/json/v3/documentation#DNS%20Create%20Record) give this example:
```
URI Endpoint: https://api.porkbun.com/api/json/v3/dns/create/DOMAIN

URI Endpoint Example: https://api.porkbun.com/api/json/v3/dns/create/borseth.ink

JSON Command Example

{
	"secretapikey": "YOUR_SECRET_API_KEY",
	"apikey": "YOUR_API_KEY",
	"name": "www",
	"type": "A",
	"content": "1.1.1.1",
	"ttl": "600"
}

JSON Response Example

{
	"status": "SUCCESS",
	"id": "106926659"
}
```
The "id" field should be a string and I am pretty sure it was when I tested the code. Could it be an undocumented change?

**Comment by apple314159** [comment]
Oh, maybe there's a change. Today is my first use of the API. You can see there are no quotes on the number.

**Comment by RLado** [comment]
Tomorrow I will try to replicate your error with my 1.22 compiled version and report back. Anyway that's a good catch, thank you for opening an issue.

**Comment by RLado** [comment]
> Oh, maybe there's a change. Today is my first use of the API. You can see there are no quotes on the number.

Clearly there are no quotes on the number. Sorry that the code did not work for you.

**Comment by RLado** [comment]
Ok, I just tested with my Go 1.22 compiled version and I can confirm that it is not an issue with Go. I am getting the same issue as you do when creating a new record (updating should be fine):
`2024/08/30 23:44:18 error decoding API response: json: cannot unmarshal number into Go struct field statusResp.id of type string (status: 200)`

Maybe I should ask Porkbun support to confirm if the change is intentional and then change the code.

**Comment by apple314159** [comment]
I've asked Portbun support. Maybe I'll get a response tomorrow.

Perhaps a better approach is to do something like this:
https://stackoverflow.com/questions/56394456/unmarshal-json-field-is-int-or-string

It's not a big deal as the id is not used for much.

**Comment by apple314159** [comment]
Porkbun will respond this week to my question on the API change.
To be more resilient and avoid the problem, it's easier to define
the id as a json.Number instead of string:
`--- a/src/main.go
+++ b/src/main.go
@@ -50,7 +50,7 @@ type ip struct {
 // Response types
 type statusResp struct {
        Status  string `json:"status"`
-       Id      string `json:"id"`
+       Id      json.Number `json:"id"`
        Message string `json:"message"`
 }
`

**Comment by RLado** [comment]
That is an elegant solution. I think you are right, regardless of Porkbun's response I think this change would be a net benefit. Do you want to make a pull request with the change?

**Comment by RLado** [comment]
Update: Porkbun support never got back to me with an answer regarding this, I'll assume this was an intentional change.
