### ISSUE TITLE
Read (Secret) API Key from environment

### ISSUE THREAD

**Issue by lunik1** [RLado/Oink#9]
Hello, would it be possible to support reading API keys from the environment rather than from the configuration file? This would be useful in the NixOS module (see https://github.com/NixOS/nixpkgs/issues/340376) where the configuration files are world-readable.

**Comment by RLado** [comment]
Hi! I have added the possibility to override the global API keys using `OINK_OVERRIDE_SECRETAPIKEY` and `OINK_OVERRIDE_APIKEY` environment variables. Let me know if this addresses your use case.

**Comment by lunik1** [comment]
Should be perfect, tysm!
